targets:
  # The 'prod' target, used for production deployment.
  prod:
    # For production deployments, we only have a single copy, so we override the
    # workspace.root_path default of
    # /Users/${workspace.current_user.userName}/.bundle/${bundle.target}/${bundle.name}
    # to a path that is not specific to the current user.
    mode: production
    workspace:
      host: https://adb-3490935972611006.6.azuredatabricks.net/
      root_path: /Users/${workspace.current_user.userName}/.bundle/${bundle.name}
    variables:
      warehouse_id:
        lookup:
          # by default sql warehouse is sql-warehouse
          # if pro warehouse is needed then sql-warehouse-pro
          # type is not provided
          # sql-warehouse (this is serverless)
          warehouse: warehouse-data-services-prod # sql-warehouse
